# Generated by Django 4.2.6 on 2023-10-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('title', models.CharField(max_length=50, verbose_name='título')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='valor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
