# Generated by Django 4.2.6 on 2023-10-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_options_alter_expense_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('c', 'Cancelado')], default='A', max_length=1),
        ),
    ]
