# Generated by Django 4.2.6 on 2023-10-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
